Make ApResolver use the proxy (if there's one configured)
librespot-org/librespot-java pull request #441
Opened 2021-12-20 22:41 UTC by Iscle

With the old implementation, the ap request wasn't going through the proxy (if there was one configured). Now, it uses the OkHttpClient we use in other parts of the app which will be configured to use the proxy if needed.

2021-12-20 22:44 UTC, Iscle commented
I have no idea why the checks have failed, it builds on my machine...

2021-12-22 21:00 UTC, devgianlu requested changes

2021-12-22 21:00 UTC, devgianlu commented on lib/src/main/java/xyz/gianlu/librespot/core/ApResolver.java
> +    private List<String> getUrls(@NotNull JsonObject body, @NotNull String type) {
This one can stay static.

2021-12-22 21:00 UTC, devgianlu commented on lib/src/main/java/xyz/gianlu/librespot/core/ApResolver.java
> +            try (Reader reader = response.body().charStream()) {
Please use a try catch block to make the request. Like this:
https://github.com/librespot-org/librespot-java/blob/31641ce3d87e51dfa8a4cf7ecf1aace46bb441fc/lib/src/main/java/xyz/gianlu/librespot/core/Login5Api.java#L111-L119

2021-12-22 21:24 UTC, Iscle commented
Fixed!

2021-12-22 21:43 UTC, devgianlu approved these changes

2021-12-22 21:43 UTC, merged